export const ROLES = {
  ADMIN: 'admin',
  LAWYER: 'lawyer',
  INTERN: 'intern',
  SECRETARY: 'secretary',
};

export const ROLES_LIST = Object.values(ROLES);

export const PERMISSIONS = {
  [ROLES.ADMIN]: ['all'],
  [ROLES.LAWYER]: [
    'view_clients',
    'create_clients',
    'edit_clients',
    'view_cases',
    'create_cases',
    'edit_cases',
    'view_documents',
    'upload_documents',
    'edit_documents',
    'view_tasks',
    'create_tasks',
    'edit_tasks',
    'view_events',
    'create_events',
    'edit_events',
    'view_payments',
    'create_payments',
    'edit_payments',
    'view_notes',
    'create_notes',
    'edit_notes',
    'use_ai',
  ],
  [ROLES.INTERN]: [
    'view_clients',
    'view_cases',
    'view_documents',
    'view_tasks',
    'view_events',
    'view_notes',
    'view_payments',
  ],
  [ROLES.SECRETARY]: [
    'view_clients',
    'create_clients',
    'edit_clients',
    'view_cases',
    'view_documents',
    'upload_documents',
    'view_tasks',
    'create_tasks',
    'view_events',
    'create_events',
    'edit_events',
    'view_payments',
    'create_payments',
    'view_notes',
    'create_notes',
  ],
};